# Autogenerated wrapper script for OpenCV_jll for i686-w64-mingw32-cxx03
export libopencv_calib3d, libopencv_core, libopencv_dnn, libopencv_features2d, libopencv_flann, libopencv_gapi, libopencv_highgui, libopencv_imgcodecs, libopencv_imgproc, libopencv_julia, libopencv_objdetect, libopencv_stitching, libopencv_video, libopencv_videoio

using Qt5Base_jll
using Libglvnd_jll
using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("OpenCV")
JLLWrappers.@declare_library_product(libopencv_calib3d, "libopencv_calib3d452.dll")
JLLWrappers.@declare_library_product(libopencv_core, "libopencv_core452.dll")
JLLWrappers.@declare_library_product(libopencv_dnn, "libopencv_dnn452.dll")
JLLWrappers.@declare_library_product(libopencv_features2d, "libopencv_features2d452.dll")
JLLWrappers.@declare_library_product(libopencv_flann, "libopencv_flann452.dll")
JLLWrappers.@declare_library_product(libopencv_gapi, "libopencv_gapi452.dll")
JLLWrappers.@declare_library_product(libopencv_highgui, "libopencv_highgui452.dll")
JLLWrappers.@declare_library_product(libopencv_imgcodecs, "libopencv_imgcodecs452.dll")
JLLWrappers.@declare_library_product(libopencv_imgproc, "libopencv_imgproc452.dll")
JLLWrappers.@declare_library_product(libopencv_julia, "libopencv_julia.dll")
JLLWrappers.@declare_library_product(libopencv_objdetect, "libopencv_objdetect452.dll")
JLLWrappers.@declare_library_product(libopencv_stitching, "libopencv_stitching452.dll")
JLLWrappers.@declare_library_product(libopencv_video, "libopencv_video452.dll")
JLLWrappers.@declare_library_product(libopencv_videoio, "libopencv_videoio452.dll")
function __init__()
    JLLWrappers.@generate_init_header(Qt5Base_jll, Libglvnd_jll, libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libopencv_calib3d,
        "bin\\libopencv_calib3d452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_core,
        "bin\\libopencv_core452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_dnn,
        "bin\\libopencv_dnn452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_features2d,
        "bin\\libopencv_features2d452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_flann,
        "bin\\libopencv_flann452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_gapi,
        "bin\\libopencv_gapi452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_highgui,
        "bin\\libopencv_highgui452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_imgcodecs,
        "bin\\libopencv_imgcodecs452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_imgproc,
        "bin\\libopencv_imgproc452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_julia,
        "bin\\libopencv_julia.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_objdetect,
        "bin\\libopencv_objdetect452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_stitching,
        "bin\\libopencv_stitching452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_video,
        "bin\\libopencv_video452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_videoio,
        "bin\\libopencv_videoio452.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
